name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install valgrind and cpplint
      run: |
        sudo apt install -y valgrind
        sudo pip3 install cpplint
    
    - name: building and testing
      run: |
        for d in */ ; do
        cd "$d"
        make
        cd ..
        done
    - name: сс
      uses: codecov/codecov-action@v1
      with:
        files: |
          ./7/main.cpp.gcov


