name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install valgrind and cpplint
      run: |
        sudo apt install -y valgrind
        sudo pip install cpplint
    
    - name: building and testing
      run: |
        cd 1
        make
