name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install valgrind and cpplint
      run: |
        sudo apt install -y valgrind
        sudo pip3 install cpplint
    
    - name: building and testing
      run: |
        for d in */ ; do
        cd "$d"
        make
        cd ..
        done
    - name: cover
      working-directory:
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.TOKEN }}
        files: ./main.gcno
        directory: ./coverage/reports/
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true

